IMAGE="../datas/timg.jpg"

BBOX_TOP_LEFT_X=175
BBOX_TOP_LEFT_Y=30
BBOX_W=250
BBOX_H=270

ROTATE_ANGLE=20

OUT_W=250
OUT_H=270

./build/AffiEx \
  $IMAGE $BBOX_TOP_LEFT_X $BBOX_TOP_LEFT_Y $BBOX_W $BBOX_H $ROTATE_ANGLE $OUT_W $OUT_H 
