IMAGE="../datas/timg.jpg"
OUT_PATH="../datas/cropped.jpg"

BBOX_TOP_LEFT_X=175
BBOX_TOP_LEFT_Y=30
BBOX_W=250
BBOX_H=270

OUT_W=125
OUT_H=135

ROTATE_ANGLE=20
SHEAR_FACTOER=0.2

./build/AffiEx \
  $IMAGE $BBOX_TOP_LEFT_X $BBOX_TOP_LEFT_Y $BBOX_W $BBOX_H $ROTATE_ANGLE $SHEAR_FACTOER $OUT_W $OUT_H $OUT_PATH
